### ISSUE TITLE
errors occur when running cutler/demo/demo.py 

### ISSUE THREAD

**Issue by lukkaal** [facebookresearch/CutLER#27]
hey! Thanks for ur work! I came across a problem when I try to run the demo.py in the "cutler/demo" file. I download the detectron2 with Linux instruction (**torch 1.10/ cuda 11.3**) and the **detectron2 version is 0.6**.
the errors can be described as below: when I follwed the instruction to run the demo.py of "cutler"

Traceback (most recent call last):
  File "demo/demo.py", line 23, in <module>
    from predictor import VisualizationDemo
  File "/root/data/CUTLER_LUKA/CutLER/cutler/demo/predictor.py", line 12, in <module>
    from engine.defaults import DefaultPredictor
  File "/root/data/CUTLER_LUKA/CutLER/cutler/./engine/__init__.py", line 7, in <module>
    from .defaults import *
  File "/root/data/CUTLER_LUKA/CutLER/cutler/./engine/defaults.py", line 41, in <module>
    from modeling import build_model
  File "/root/data/CUTLER_LUKA/CutLER/cutler/./modeling/__init__.py", line 3, in <module>
    from .roi_heads import (
  File "/root/data/CUTLER_LUKA/CutLER/cutler/./modeling/roi_heads/__init__.py", line 3, in <module>
    from .roi_heads import (
  File "/root/data/CUTLER_LUKA/CutLER/cutler/./modeling/roi_heads/roi_heads.py", line 25, in <module>
    from .fast_rcnn import FastRCNNOutputLayers
  File "/root/data/CUTLER_LUKA/CutLER/cutler/./modeling/roi_heads/fast_rcnn.py", line 11, in <module>
    from detectron2.data.detection_utils import get_fed_loss_cls_weights
_ImportError: cannot import name 'get_fed_loss_cls_weights' from 'detectron2.data.detection_utils' (/opt/conda/envs/CUTLER/lib/python3.8/site-packages/detectron2/data/detection_utils.py)_

**Comment by frank-xwang** [comment]
Hi, have you followed the instructions in [CutLER/INSTALL](https://github.com/facebookresearch/CutLER/blob/main/INSTALL.md) to install all the required packages? It seems like the error occurred because the model was unable to import the function "[get_fed_loss_cls_weights](https://github.com/facebookresearch/detectron2/blob/ebb26b5b0d914a9fc196da303e536892165a7113/detectron2/data/detection_utils.py#L547)" from the "detectron2/data/detection_utils.py" file, which should work correctly if you have installed detectron2 properly.
